import { buildEmailShell, escapeHtml } from "./emailTemplate";
import type { BrandingContext } from "./branding";
import { getDefaultBranding } from "./branding";

export function buildAgentReplyEmail(
  responseBody: string,
  branding: BrandingContext = getDefaultBranding(),
): { html: string; text: string } {
  // Convert markdown-ish response to HTML paragraphs
  const htmlBody = responseBody
    .split("\n\n")
    .map((block) => {
      const trimmed = block.trim();
      if (!trimmed) return "";

      // Convert markdown links [text](url) to <a> tags
      const withLinks = trimmed.replace(
        /\[([^\]]+)\]\(([^)]+)\)/g,
        '<a href="$2" class="glass-email-link" style="color:#2563eb;text-decoration:underline;">$1</a>',
      );

      // Handle bullet points
      if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        const items = trimmed
          .split("\n")
          .filter((line) => line.trim())
          .map((line) => {
            const content = line.replace(/^[-*]\s+/, "");
            const withItemLinks = content.replace(
              /\[([^\]]+)\]\(([^)]+)\)/g,
              '<a href="$2" class="glass-email-link" style="color:#2563eb;text-decoration:underline;">$1</a>',
            );
            return `<li style="margin:4px 0;">${withItemLinks}</li>`;
          })
          .join("");
        return `<ul style="margin:0 0 0 20px;padding:0;">${items}</ul>`;
      }

      // Bold text
      const withBold = withLinks.replace(
        /\*\*([^*]+)\*\*/g,
        "<strong>$1</strong>",
      );

      // Inline line breaks
      const withBreaks = withBold.replace(/\n/g, "<br>");

      return `<p class="glass-email-text-secondary" style="margin:0 0 12px 0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:14px;color:#000000;line-height:1.6;">${withBreaks}</p>`;
    })
    .filter(Boolean)
    .join("");

  const bodyHtml = `
<tr><td class="glass-email-text-secondary" style="padding:24px 32px 0 32px;">
  ${htmlBody}
</td></tr>
<tr><td style="padding:20px 32px 0 32px;">
  <div class="glass-email-divider" style="height:1px;background-color:rgba(17,24,39,0.06);"></div>
</td></tr>
<tr><td align="center" style="padding:16px 32px 24px 32px;">
  <p class="glass-email-text-muted" style="margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:11px;color:#9ca3af;line-height:1.5;">
    Generated by ${branding.agentDisplayName} from your extracted policy documents.
  </p>
</td></tr>`;
  const html = buildEmailShell({
    title: `${escapeHtml(branding.brandName)} Response`,
    bodyHtml,
    branding,
  });

  return { html, text: responseBody };
}
