export function buildAgentReplyEmail(
  responseBody: string,
  siteUrl: string,
): { html: string; text: string } {
  const logoUrl = `${siteUrl}/clarity-labs-logo.jpg`;

  // Convert markdown-ish response to HTML paragraphs
  const htmlBody = responseBody
    .split("\n\n")
    .map((block) => {
      const trimmed = block.trim();
      if (!trimmed) return "";

      // Convert markdown links [text](url) to <a> tags
      const withLinks = trimmed.replace(
        /\[([^\]]+)\]\(([^)]+)\)/g,
        '<a href="$2" style="color:#2563eb;text-decoration:underline;">$1</a>',
      );

      // Handle bullet points
      if (trimmed.startsWith("- ") || trimmed.startsWith("* ")) {
        const items = trimmed
          .split("\n")
          .filter((line) => line.trim())
          .map((line) => {
            const content = line.replace(/^[-*]\s+/, "");
            const withItemLinks = content.replace(
              /\[([^\]]+)\]\(([^)]+)\)/g,
              '<a href="$2" style="color:#2563eb;text-decoration:underline;">$1</a>',
            );
            return `<li style="margin:4px 0;">${withItemLinks}</li>`;
          })
          .join("");
        return `<ul style="margin:0 0 0 20px;padding:0;">${items}</ul>`;
      }

      // Bold text
      const withBold = withLinks.replace(
        /\*\*([^*]+)\*\*/g,
        "<strong>$1</strong>",
      );

      // Inline line breaks
      const withBreaks = withBold.replace(/\n/g, "<br>");

      return `<p style="margin:0 0 12px 0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:14px;color:#111827;line-height:1.6;">${withBreaks}</p>`;
    })
    .filter(Boolean)
    .join("");

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="color-scheme" content="light">
<title>Clarity Agent Response</title>
</head>
<body style="margin:0;padding:0;background-color:#faf8f4;-webkit-text-size-adjust:100%;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#faf8f4;">
<tr><td align="center" style="padding:32px 16px;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;background-color:#ffffff;border-radius:12px;border:1px solid rgba(17,24,39,0.06);box-shadow:0 1px 3px rgba(0,0,0,0.04);">

<!-- Logo -->
<tr><td align="center" style="padding:28px 32px 0 32px;">
  <img src="${logoUrl}" alt="Clarity Labs" width="140" height="auto" style="display:block;width:140px;height:auto;border:0;" />
</td></tr>

<!-- Body -->
<tr><td style="padding:24px 32px 0 32px;">
  ${htmlBody}
</td></tr>

<!-- Divider -->
<tr><td style="padding:20px 32px 0 32px;">
  <div style="height:1px;background-color:rgba(17,24,39,0.06);"></div>
</td></tr>

<!-- Footer -->
<tr><td align="center" style="padding:16px 32px 24px 32px;">
  <p style="margin:0;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;font-size:11px;color:#9ca3af;line-height:1.5;">
    Generated by Clarity Agent from your extracted policy documents.
  </p>
</td></tr>

</table>
</td></tr>
</table>
</body>
</html>`;

  return { html, text: responseBody };
}
