export type ModelTask =
  | "chat"
  | "email_draft"
  | "email_reply"
  | "extraction"
  | "classification"
  | "analysis"
  | "summary"
  | "triage"
  | "email_extraction"
  | "document_extraction"
  | "security"
  | "mailbox_coordinator"
  | "application_authoring"
  | "embeddings";

export type ModelProvider =
  | "openai"
  | "anthropic"
  | "google"
  | "xai"
  | "mistral"
  | "cohere"
  | "moonshot"
  | "deepseek";

export type ModelRoute = {
  provider: ModelProvider;
  model: string;
};

export type ModelCapabilityConfig = {
  modelName: string;
  maxInputTokens?: number;
  maxOutputTokens?: number;
  defaultOutputTokens?: number;
  longListOutputTokens?: number;
  taskOutputTokens?: Record<string, number>;
};

export const PROVIDER_LABELS: Record<ModelProvider, string> = {
  openai: "OpenAI",
  anthropic: "Anthropic",
  google: "Google",
  xai: "xAI",
  mistral: "Mistral",
  cohere: "Cohere",
  moonshot: "Disabled provider",
  deepseek: "DeepSeek",
};

export const MODEL_TASK_LABELS: Record<ModelTask, string> = {
  chat: "Chat assistant",
  email_draft: "Email drafting",
  email_reply: "Inbound email replies",
  extraction: "Policy extraction",
  classification: "Document classification",
  analysis: "Analysis",
  summary: "Summaries and memory",
  triage: "Website enrichment",
  email_extraction: "Email extraction",
  document_extraction: "Document extraction",
  security: "Security checks",
  mailbox_coordinator: "Mailbox coordinator",
  application_authoring: "Application authoring",
  embeddings: "Embeddings",
};

export const MODEL_TASK_DESCRIPTIONS: Record<ModelTask, string> = {
  chat: "Web chat, broker assistant workflows, and tool calling.",
  email_draft: "Outbound email drafts created from chat.",
  email_reply: "Replies generated by the inbound email agent.",
  extraction: "Structured policy and quote extraction from PDFs.",
  classification: "Fast document and request classification.",
  analysis: "Coverage reasoning and reconciliation passes.",
  summary: "Conversation, email, and organization memory summaries.",
  triage: "Company website enrichment during onboarding.",
  email_extraction: "Low-cost extraction from email content.",
  document_extraction: "Document-level extraction subtasks.",
  security: "Prompt-injection and unsafe request classification.",
  mailbox_coordinator: "Complex connected-mailbox workflows that search email, inspect attachments, import policies or requirements, and coordinate follow-up actions.",
  application_authoring: "Application or questionnaire drafting.",
  embeddings: "Vector search embeddings for policies and conversation memory.",
};

export const LANGUAGE_MODEL_CATALOG: Record<ModelProvider, string[]> = {
  openai: [
    "gpt-5.5",
    "gpt-5.5-pro",
    "gpt-5.4",
    "gpt-5.4-mini",
    "gpt-5.4-nano",
    "gpt-5.4-pro",
    "gpt-5.3-chat",
    "gpt-5.3-codex",
    "gpt-5.2",
    "gpt-5.2-chat",
    "gpt-5.2-codex",
    "gpt-5.2-pro",
    "gpt-5.1-instant",
    "gpt-5.1-thinking",
    "gpt-5.1-codex",
    "gpt-5.1-codex-mini",
    "gpt-5.1-codex-max",
    "gpt-5",
    "gpt-5-chat",
    "gpt-5-mini",
    "gpt-5-nano",
    "gpt-5-pro",
    "gpt-5-codex",
    "gpt-4.1",
    "gpt-4.1-mini",
    "gpt-4.1-nano",
    "gpt-4o",
    "gpt-4o-mini",
    "o4-mini",
    "o3",
    "o3-mini",
    "o3-pro",
  ],
  anthropic: [
    "claude-opus-4.7",
    "claude-opus-4.6",
    "claude-opus-4.5",
    "claude-opus-4.1",
    "claude-opus-4",
    "claude-sonnet-4.6",
    "claude-sonnet-4.5",
    "claude-sonnet-4",
    "claude-haiku-4.5",
    "claude-3.5-haiku",
    "claude-3-haiku",
  ],
  google: [
    "gemini-3.5-flash",
    "gemini-3.1-pro-preview",
    "gemini-3.1-flash-lite",
    "gemini-3.1-flash-lite-preview",
    "gemini-3.1-flash-image-preview",
    "gemini-3-pro-preview",
    "gemini-3-pro-image",
    "gemini-3-flash",
    "gemini-2.5-pro",
    "gemini-2.5-flash",
    "gemini-2.5-flash-lite",
    "gemini-2.5-flash-image",
    "gemini-2.0-flash",
    "gemini-2.0-flash-lite",
    "gemma-4-31b-it",
    "gemma-4-26b-a4b-it",
  ],
  xai: [
    "grok-4.3",
    "grok-4.20-reasoning",
    "grok-4.20-non-reasoning",
    "grok-4.20-multi-agent",
    "grok-4.20-reasoning-beta",
    "grok-4.20-non-reasoning-beta",
    "grok-4.20-multi-agent-beta",
    "grok-4.1-fast-reasoning",
    "grok-4.1-fast-non-reasoning",
    "grok-build-0.1",
  ],
  mistral: [
    "mistral-large-3",
    "mistral-medium-3.5",
    "mistral-medium",
    "mistral-small",
    "mistral-nemo",
    "magistral-medium",
    "magistral-small",
    "ministral-14b",
    "ministral-8b",
    "ministral-3b",
    "devstral-2",
    "devstral-small-2",
    "devstral-small",
    "codestral",
    "pixtral-large",
    "pixtral-12b",
  ],
  cohere: ["command-a"],
  moonshot: [],
  deepseek: [
    "deepseek-v4-pro",
    "deepseek-v4-flash",
    "deepseek-v3.2-thinking",
    "deepseek-v3.2",
    "deepseek-v3.1-terminus",
    "deepseek-v3.1",
    "deepseek-v3",
    "deepseek-r1",
  ],
};

export const EMBEDDING_MODEL_CATALOG: Partial<Record<ModelProvider, string[]>> = {
  openai: ["text-embedding-3-small", "text-embedding-3-large"],
};

export const MODEL_ROUTING: Record<ModelTask, ModelRoute> = {
  chat: { model: "gpt-5.4-mini", provider: "openai" },
  email_draft: { model: "gpt-5.4-mini", provider: "openai" },
  email_reply: { model: "gpt-5.4-mini", provider: "openai" },
  analysis: { model: "gpt-5.4-mini", provider: "openai" },
  summary: { model: "gpt-5.4-mini", provider: "openai" },
  classification: { model: "gpt-5.4-nano", provider: "openai" },
  extraction: { model: "gpt-5.4-nano", provider: "openai" },
  triage: { model: "gpt-5.4-mini", provider: "openai" },
  email_extraction: { model: "gpt-5.4-nano", provider: "openai" },
  document_extraction: { model: "gpt-5.4-nano", provider: "openai" },
  security: { model: "gpt-5.4-mini", provider: "openai" },
  mailbox_coordinator: { model: "gpt-5.5", provider: "openai" },
  application_authoring: { model: "gpt-5.4-mini", provider: "openai" },
  embeddings: { model: "text-embedding-3-small", provider: "openai" },
};

export const FALLBACK_MODEL: ModelRoute = { model: "gpt-5.4-mini", provider: "openai" };

export const MODEL_TASKS = Object.keys(MODEL_ROUTING) as ModelTask[];
export const MODEL_PROVIDERS = Object.keys(PROVIDER_LABELS) as ModelProvider[];
export const CONFIGURABLE_MODEL_PROVIDERS = MODEL_PROVIDERS.filter(
  (provider) => provider !== "moonshot",
) as Exclude<ModelProvider, "moonshot">[];

export const MODEL_CAPABILITIES: Record<string, ModelCapabilityConfig> = {
  "gpt-5.5": {
    modelName: "gpt-5.5",
    maxInputTokens: 400_000,
    maxOutputTokens: 32_768,
    defaultOutputTokens: 8_192,
    longListOutputTokens: 24_576,
    taskOutputTokens: {
      extraction_classify: 2_048,
      extraction_form_inventory: 8_192,
      extraction_page_map: 8_192,
      extraction_focused: 16_384,
      extraction_long_list: 24_576,
      extraction_review: 12_288,
      query_reason: 8_192,
      query_verify: 4_096,
      pce_impact_analysis: 8_192,
      pce_packet_generation: 8_192,
    },
  },
  "gpt-5.4": {
    modelName: "gpt-5.4",
    maxInputTokens: 400_000,
    maxOutputTokens: 32_768,
    defaultOutputTokens: 8_192,
    longListOutputTokens: 24_576,
  },
  "gpt-5.4-mini": {
    modelName: "gpt-5.4-mini",
    maxInputTokens: 400_000,
    maxOutputTokens: 32_768,
    defaultOutputTokens: 8_192,
    longListOutputTokens: 24_576,
  },
  "gpt-5.4-nano": {
    modelName: "gpt-5.4-nano",
    maxInputTokens: 400_000,
    maxOutputTokens: 32_768,
    defaultOutputTokens: 8_192,
    longListOutputTokens: 24_576,
  },
  "claude-haiku-4-5-20251001": {
    modelName: "claude-haiku-4-5-20251001",
    maxInputTokens: 200_000,
    maxOutputTokens: 8_192,
    defaultOutputTokens: 4_096,
    longListOutputTokens: 8_192,
  },
};

export function modelCapabilitiesForRoute(route: ModelRoute): ModelCapabilityConfig | undefined {
  return MODEL_CAPABILITIES[route.model] ?? {
    modelName: route.model,
    defaultOutputTokens: 4_096,
  };
}

export function modelCapabilitiesForTask(task: ModelTask): ModelCapabilityConfig | undefined {
  return modelCapabilitiesForRoute(MODEL_ROUTING[task]);
}
