export const POLICY_TYPE_LABELS: Record<string, string> = {
  general_liability: "General Liability",
  commercial_property: "Commercial Property",
  commercial_auto: "Commercial Auto",
  non_owned_auto: "Non-Owned Auto",
  workers_comp: "Workers' Compensation",
  umbrella: "Umbrella",
  excess_liability: "Excess Liability",
  professional_liability: "Professional Liability",
  cyber: "Cyber",
  epli: "EPLI",
  directors_officers: "Directors & Officers",
  fiduciary_liability: "Fiduciary Liability",
  crime_fidelity: "Crime & Fidelity",
  inland_marine: "Inland Marine",
  builders_risk: "Builders Risk",
  environmental: "Environmental",
  ocean_marine: "Ocean Marine",
  surety: "Surety",
  product_liability: "Product Liability",
  bop: "Business Owners Policy",
  management_liability_package: "Management Liability Package",
  property: "Property",
  other: "Other",
};

export const INSURANCE_KEYWORDS = [
  // Core terms
  "insurance",
  "policy",
  "coverage",
  "premium",
  "renewal",
  "certificate",
  "endorsement",
  "declaration",
  "binder",
  "liability",
  "deductible",
  "claim",
  "underwriting",
  "indemnity",
  "insured",
  "policyholder",
  "COI",
  "certificate of insurance",
  // Policy types
  "workers comp",
  "workers compensation",
  "commercial auto",
  "general liability",
  "umbrella",
  "property insurance",
  "cyber insurance",
  "professional liability",
  "errors and omissions",
  "directors and officers",
  "d&o",
  "epli",
  "non-owned auto",
  "hired auto",
  "inland marine",
  "ocean marine",
  "builders risk",
  "surety bond",
  "fidelity bond",
  "crime insurance",
  "pollution liability",
  "environmental liability",
  "excess liability",
  "fiduciary liability",
  "employment practices",
  "media liability",
  "tech e&o",
  "product liability",
  "completed operations",
  // Documents & actions
  "policy document",
  "insurance certificate",
  "dec page",
  "declarations page",
  "schedule of insurance",
  "loss run",
  "loss history",
  "acord",
  "quote proposal",
  "insurance proposal",
  "insurance quote",
  "indication",
  "submission",
  "policy renewal",
  "insurance renewal",
  "policy expir",
  "coverage bound",
  "bound coverage",
  "notice of cancellation",
  "reinstatement",
  "audit premium",
  "retrospective premium",
  "experience mod",
  "insurance audit",
];

// Policy section type labels and colors
export const POLICY_SECTION_TYPE_LABELS: Record<string, string> = {
  declarations: "Declarations",
  insuring_agreement: "Insuring Agreement",
  policy_form: "Policy Form",
  endorsement: "Endorsement",
  application: "Application",
  exclusion: "Exclusion",
  condition: "Condition",
  definition: "Definition",
  schedule: "Schedule",
  subjectivity: "Subjectivity",
  warranty: "Warranty",
  notice: "Notice",
  regulatory: "Regulatory",
  other: "Other",
};

export const POLICY_SECTION_TYPE_COLORS: Record<string, string> = {
  declarations: "bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400",
  insuring_agreement: "bg-green-50 dark:bg-green-950/40 text-green-600 dark:text-green-400",
  policy_form: "bg-cyan-50 dark:bg-cyan-950/40 text-cyan-600 dark:text-cyan-400",
  endorsement: "bg-sky-50 dark:bg-sky-950/40 text-sky-600 dark:text-sky-400",
  application: "bg-lime-50 dark:bg-lime-950/40 text-lime-600 dark:text-lime-400",
  exclusion: "bg-red-50 dark:bg-red-950/40 text-red-600 dark:text-red-400",
  condition: "bg-amber-50 dark:bg-amber-950/40 text-amber-600 dark:text-amber-400",
  definition: "bg-purple-50 dark:bg-purple-950/40 text-purple-600 dark:text-purple-400",
  schedule: "bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400",
  subjectivity: "bg-orange-50 dark:bg-orange-950/40 text-orange-600 dark:text-orange-400",
  warranty: "bg-pink-50 dark:bg-pink-950/40 text-pink-600 dark:text-pink-400",
  notice: "bg-teal-50 dark:bg-teal-950/40 text-teal-600 dark:text-teal-400",
  regulatory: "bg-yellow-50 dark:bg-yellow-950/40 text-yellow-700 dark:text-yellow-400",
  other: "bg-gray-50 dark:bg-gray-800/40 text-gray-600 dark:text-gray-400",
};

// Quote section type labels and colors
export const QUOTE_SECTION_TYPE_LABELS: Record<string, string> = {
  terms_summary: "Terms Summary",
  premium_indication: "Premium Indication",
  underwriting_condition: "Underwriting Condition",
  subjectivity: "Subjectivity",
  coverage_summary: "Coverage Summary",
  exclusion: "Exclusion",
  other: "Other",
};

export const QUOTE_SECTION_TYPE_COLORS: Record<string, string> = {
  terms_summary: "bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400",
  premium_indication: "bg-emerald-50 dark:bg-emerald-950/40 text-emerald-600 dark:text-emerald-400",
  underwriting_condition: "bg-amber-50 dark:bg-amber-950/40 text-amber-600 dark:text-amber-400",
  subjectivity: "bg-orange-50 dark:bg-orange-950/40 text-orange-600 dark:text-orange-400",
  coverage_summary: "bg-green-50 dark:bg-green-950/40 text-green-600 dark:text-green-400",
  exclusion: "bg-red-50 dark:bg-red-950/40 text-red-600 dark:text-red-400",
  other: "bg-gray-50 dark:bg-gray-800/40 text-gray-600 dark:text-gray-400",
};

export const INSURANCE_SENDER_PATTERNS = [
  // Major carriers
  "hartford",
  "liberty mutual",
  "libertymutual",
  "travelers",
  "chubb",
  "nationwide",
  "state farm",
  "statefarm",
  "allstate",
  "progressive",
  "zurich",
  "aig",
  "berkshire",
  "geico",
  "usaa",
  "erie insurance",
  "hanover",
  "markel",
  "hiscox",
  "amtrust",
  "tokio marine",
  "allianz",
  "aviva",
  "intact",
  "wawanesa",
  "co-operators",
  "economical",
  "definity",
  "northbridge",
  "federated",
  "rsa",
  "lloyds",
  "lloyd's",
  "scotialife",
  "manulife",
  "sunlife",
  "great-west",
  "industrial alliance",
  "gore mutual",
  "pembridge",
  "facility association",
  // Brokers & MGAs
  "marsh",
  "aon",
  "gallagher",
  "ajg",
  "willis towers",
  "wtw",
  "hub international",
  "hubinternational",
  "lockton",
  "brown & brown",
  "acrisure",
  "usi",
  "nfu mutual",
  "jones desaulniers",
  "bfl canada",
  // Generic patterns (domain/name substrings)
  "insurance",
  "insuranc",
  "insurer",
  "underwriter",
  "underwriting",
  "broker",
  "brokerage",
  "surety",
  "actuari",
  "risk management",
  "riskmanagement",
];
