export const INSURANCE_KEYWORDS = [
  // Core terms
  "insurance",
  "policy",
  "coverage",
  "premium",
  "renewal",
  "certificate",
  "endorsement",
  "declaration",
  "binder",
  "liability",
  "deductible",
  "claim",
  "underwriting",
  "indemnity",
  "insured",
  "policyholder",
  "COI",
  "certificate of insurance",
  // Policy types
  "workers comp",
  "workers compensation",
  "commercial auto",
  "general liability",
  "umbrella",
  "property insurance",
  "cyber insurance",
  "professional liability",
  "errors and omissions",
  "directors and officers",
  "d&o",
  "epli",
  "non-owned auto",
  "hired auto",
  "inland marine",
  "ocean marine",
  "builders risk",
  "surety bond",
  "fidelity bond",
  "crime insurance",
  "pollution liability",
  "environmental liability",
  "excess liability",
  "fiduciary liability",
  "employment practices",
  "media liability",
  "tech e&o",
  "product liability",
  "completed operations",
  // Personal lines
  "homeowners",
  "home insurance",
  "renters insurance",
  "condo insurance",
  "dwelling fire",
  "personal auto",
  "auto insurance",
  "car insurance",
  "flood insurance",
  "earthquake insurance",
  "personal umbrella",
  "personal articles",
  "watercraft",
  "boat insurance",
  "recreational vehicle",
  "rv insurance",
  "farm insurance",
  "ranch insurance",
  "life insurance",
  "permanent life",
  "term life",
  "critical illness",
  "disability insurance",
  "long term care",
  "pet insurance",
  "travel insurance",
  "identity theft",
  "title insurance",
  "mobile home",
  "manufactured home",
  // Documents & actions
  "policy document",
  "insurance certificate",
  "dec page",
  "declarations page",
  "schedule of insurance",
  "loss run",
  "loss history",
  "acord",
  "insurance proposal",
  "policy renewal",
  "insurance renewal",
  "policy expir",
  "coverage bound",
  "bound coverage",
  "notice of cancellation",
  "reinstatement",
  "audit premium",
  "retrospective premium",
  "experience mod",
  "insurance audit",
];

// Policy section type labels and colors
export const POLICY_SECTION_TYPE_LABELS: Record<string, string> = {
  declarations: "Declarations",
  insuring_agreement: "Insuring Agreement",
  policy_form: "Policy Form",
  endorsement: "Endorsement",
  application: "Application",
  exclusion: "Exclusion",
  condition: "Condition",
  definition: "Definition",
  schedule: "Schedule",
  subjectivity: "Subjectivity",
  warranty: "Warranty",
  notice: "Notice",
  regulatory: "Regulatory",
  other: "Other",
};

export const POLICY_SECTION_TYPE_COLORS: Record<string, string> = {
  declarations: "bg-blue-50 dark:bg-blue-950/40 text-blue-600 dark:text-blue-400",
  insuring_agreement: "bg-green-50 dark:bg-green-950/40 text-green-600 dark:text-green-400",
  policy_form: "bg-cyan-50 dark:bg-cyan-950/40 text-cyan-600 dark:text-cyan-400",
  endorsement: "bg-sky-50 dark:bg-sky-950/40 text-sky-600 dark:text-sky-400",
  application: "bg-lime-50 dark:bg-lime-950/40 text-lime-600 dark:text-lime-400",
  exclusion: "bg-red-50 dark:bg-red-950/40 text-red-600 dark:text-red-400",
  condition: "bg-amber-50 dark:bg-amber-950/40 text-amber-600 dark:text-amber-400",
  definition: "bg-purple-50 dark:bg-purple-950/40 text-purple-600 dark:text-purple-400",
  schedule: "bg-indigo-50 dark:bg-indigo-950/40 text-indigo-600 dark:text-indigo-400",
  subjectivity: "bg-orange-50 dark:bg-orange-950/40 text-orange-600 dark:text-orange-400",
  warranty: "bg-pink-50 dark:bg-pink-950/40 text-pink-600 dark:text-pink-400",
  notice: "bg-teal-50 dark:bg-teal-950/40 text-teal-600 dark:text-teal-400",
  regulatory: "bg-yellow-50 dark:bg-yellow-950/40 text-yellow-700 dark:text-yellow-400",
  other: "bg-gray-50 dark:bg-gray-800/40 text-gray-600 dark:text-gray-400",
};

export const INSURANCE_SENDER_PATTERNS = [
  // Major carriers
  "hartford",
  "liberty mutual",
  "libertymutual",
  "travelers",
  "chubb",
  "nationwide",
  "state farm",
  "statefarm",
  "allstate",
  "progressive",
  "zurich",
  "aig",
  "berkshire",
  "geico",
  "usaa",
  "erie insurance",
  "hanover",
  "markel",
  "hiscox",
  "amtrust",
  "tokio marine",
  "allianz",
  "aviva",
  "intact",
  "wawanesa",
  "co-operators",
  "economical",
  "definity",
  "northbridge",
  "federated",
  "rsa",
  "lloyds",
  "lloyd's",
  "scotialife",
  "manulife",
  "sunlife",
  "great-west",
  "industrial alliance",
  "gore mutual",
  "pembridge",
  "facility association",
  // Brokers & MGAs
  "marsh",
  "aon",
  "gallagher",
  "ajg",
  "willis towers",
  "wtw",
  "hub international",
  "hubinternational",
  "lockton",
  "brown & brown",
  "acrisure",
  "usi",
  "nfu mutual",
  "jones desaulniers",
  "bfl canada",
  // Generic patterns (domain/name substrings)
  "insurance",
  "insuranc",
  "insurer",
  "underwriter",
  "underwriting",
  "broker",
  "brokerage",
  "surety",
  "actuari",
  "risk management",
  "riskmanagement",
];
