export const POLICY_TYPE_LABELS: Record<string, string> = {
  general_liability: "General Liability",
  workers_comp: "Workers' Compensation",
  commercial_auto: "Commercial Auto",
  property: "Property",
  umbrella: "Umbrella",
  professional_liability: "Professional Liability",
  cyber: "Cyber",
  epli: "EPLI",
  directors_officers: "Directors & Officers",
  non_owned_auto: "Non-Owned Auto",
  other: "Other",
};

export const INSURANCE_KEYWORDS = [
  "policy",
  "insurance",
  "coverage",
  "premium",
  "renewal",
  "certificate",
  "endorsement",
  "declaration",
  "binder",
  "liability",
  "deductible",
  "claim",
  "underwriting",
  "indemnity",
  "insured",
  "policyholder",
  "workers comp",
  "workers compensation",
  "commercial auto",
  "general liability",
  "umbrella",
  "property insurance",
  "cyber insurance",
  "professional liability",
  "errors and omissions",
  "directors and officers",
  "d&o",
  "epli",
  "COI",
  "certificate of insurance",
];

export const INSURANCE_SENDER_PATTERNS = [
  "hartford",
  "liberty mutual",
  "travelers",
  "chubb",
  "nationwide",
  "state farm",
  "allstate",
  "progressive",
  "zurich",
  "aig",
  "berkshire",
  "geico",
  "usaa",
  "erie insurance",
  "hanover",
  "markel",
  "hiscox",
  "amtrust",
  "insurance",
  "underwriter",
  "broker",
];
